name: Publish

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    env:
      PR: ${{ github.event.workflow_run.head_branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build
        uses: dawidd6/action-download-artifact@v3
        with:
          name: actions_artifacts
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: Get PR or branch number
        run: |
          # Проверяем, является ли ветка PR
          if [[ "${{ github.event.workflow_run.head_branch }}" == feature/* || "${{ github.event.workflow_run.head_branch }}" == hotfix/* ]]; then
            # Предполагается, что у вас есть номер PR в переменной или файле
            # Например, если есть переменная или файл с номером PR, вставьте сюда
            echo "PR=PR-$(cat env | grep 'prev.event.number' | awk -F '=' '{print $2}')" >> $GITHUB_ENV
          else
            # Для ветки, а не PR, можно оставить комментарий в ветке или пропустить
            echo "PR=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          fi
          echo "BUILD_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Deploy build to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
          git-config-name: "keksobot"
          git-config-email: "github+keksobot@htmlacademy.ru"
          target-folder: ${{ env.PR }}
          commit-message: "✔️ Сборка #${{ env.PR }}"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Ваш пулреквест опубликован. Посмотреть можно [здесь](https://${{ env.BUILD_URL }}/${{ env.PR }}/)
          pr_number: ${{ env.PR }}
